[build]
  command = "npm install && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.4"
  NODE_VERSION = "18"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"